version: 2
updates_configs:
    - package_manager: "java:maven"
      directory: "/"
      update_schedule: "daily"
      target-branch: development
      default_labels: "dependabot"
      commit-message:
          prefix: "[DEPENDABOT]"

