qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Sven Fillinger
email: sven.fillinger@qbic.uni-tuebingen.de
project_name: data-model-lib
project_short_description: "Data models. A collection of QBiC's central data models\
  \ and DTOs. "
version: 2.3.0
domain: lib
language: groovy
project_slug: data-model-lib
project_slug_no_hyphen: data_model_lib
template_version: '1.0.1 # <<QUBE_NO_BUMP>>'
template_handle: lib-groovy
github_username: qbicsoftware
creator_github_username: sven1103
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: qbicsoftware
copyright_holder: QBiC
license: MIT
