package life.qbic.datamodel.dtos.imaging.properties

/**
 * Class storing the emissions from a light source as a range of wave lengths
 *
 * This class should be used to store the range of emission patterns 
 * generated by a light source by specifiying of the start- and end- wavelength. 
 * @since: 1.10.0
 * @author: Jennifer Bödker
 *
 */
class EmissionRange {

    /**
     * Its the smallest wavelength within the emission range
     * e.g 495 nm
     */
    final int startWavelength

    /**
     * Its the biggest wavelength within the emission range
     * e.g 530 nm
     */
    final int endWavelength

    /**
     * Class storing the emissions from a light source as a range of wave lengths
     * @param startWavelength {@link EmissionRange#startWavelength}
     * @param endWavelength {@link EmissionRange#endWavelength}
     */
    EmissionRange(int startWavelength, int endWavelength) {
        this.startWavelength = startWavelength
        this.endWavelength = endWavelength
    }

    boolean equals(o) {
        if (this.is(o)) return true
        if (getClass() != o.class) return false

        EmissionRange that = (EmissionRange) o

        if (endWavelength != that.endWavelength) return false
        if (startWavelength != that.startWavelength) return false

        return true
    }

    int hashCode() {
        int result
        result = startWavelength
        result = 31 * result + endWavelength
        return result
    }
}
