package life.qbic.datamodel.dtos.imaging.properties

/**
 * Class storing the emissions from a light source as a range of wave lengths
 *
 * This class should be used to store the range of emission patterns 
 * generated by a light source by specifiying of the start- and end- wavelength. 
 * @since: 1.10.0
 * @author: Jennifer Bödker
 *
 */
class EmissionRange {

    /**
     * Its the smallest wavelength within the emission range
     * e.g 495 nm
     */
    private final int startWaveLength

    /**
     * Its the biggest wavelength within the emission range
     * e.g 530 nm
     */
    private final int endWaveLength
}
