version: 2
update_configs:
    - package_manager: "java:maven"
      directory: "/"
      update_schedule: "daily"
      target_branch: "development"
      default_labels:
          - "dependabot"
      commit_message:
          prefix: "[DEPENDABOT]"
