name: Java Checkstyle

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.31/checkstyle-8.31-all.jar

      - name: Download Google style xml
        run: wget https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.28/src/main/resources/google_checks.xml

      - name: Run Checkstyle
        run: java -jar checkstyle-8.31-all.jar -c google_checks.xml .
